### ISSUE TITLE
check uniqueness fails

### ISSUE THREAD

**Issue by lakhoune** [StudyGrow/Cards#178]
I cannot add a new lecture using the angular frontend. 
This is likely due to the fact that `lectures/check` has not yet received its gql counterparts.
The whole flow should also be reconsidered. This check should be explicitly done on the server when trying to add a new card and not be a seperate call on the frontend

**Comment by erdzan12** [comment]
agree

**Comment by lakhoune** [comment]
I remember why this was implemented this way: 
When adding a lecture, this lecture is first stored in localstorage and only if the user also adds a card, will the lecture be added on the server. This was to prevent people from creating lectures without adding cards. 
Thus this check makes sense in my opinion^^

Anyways, it is fixed
