### ISSUE TITLE
creation date

### ISSUE THREAD

**Issue by erdzan12** [StudyGrow/Cards#37]
In GitLab by @lakhoune on May 14, 2020, 22:35

add the date as a field to the cartd model and save the timestamp on which a new card  is added on the card

**Comment by erdzan12** [comment]
In GitLab by @lakhoune on May 15, 2020, 12:27

assigned to @lakhoune

**Comment by erdzan12** [comment]
In GitLab by @lakhoune on May 15, 2020, 12:28

mentioned in commit 89584353e2ea739f7bc75d2a031011f2f5f925fc

**Comment by erdzan12** [comment]
In GitLab by @lakhoune on May 15, 2020, 12:28

closed

**Comment by erdzan12** [comment]
In GitLab by @VerwaltungHilton on May 15, 2020, 22:49

Do not forget to mark the social service as verified                  [here](https://verwaltung.hilton.rwth-aachen.de/admin/association/socialservice/348)

**Comment by autoantwort** [comment]
> In GitLab by @VerwaltungHilton on May 15, 2020, 22:49
> 
> Do not forget to mark the social service as verified [here](https://verwaltung.hilton.rwth-aachen.de/admin/association/socialservice/348)

STOP SPAMMING!
